title : mistergough.com
permalinks: pretty
name: mistergough.com
description: mistergough's blog
url: http://mistergough.com/
author:
 name: mistergough
comments: true
plugins: [jekyll-paginate]
paginate: 1
